/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-tint": "#005ac4",
          "primary": "#0057bf",
          "background": "#f8f9ff",
          "inverse-primary": "#aec6ff",
          "surface-container-low": "#eff4ff",
          "error": "#ba1a1a",
          "tertiary": "#555c67",
          "surface": "#f8f9ff",
          "on-tertiary-container": "#fdfcff",
          "outline-variant": "#c2c6d6",
          "primary-fixed-dim": "#aec6ff",
          "on-tertiary-fixed-variant": "#404751",
          "primary-container": "#1770e9",
          "on-primary-fixed": "#001a42",
          "on-primary": "#ffffff",
          "surface-bright": "#f8f9ff",
          "on-secondary-container": "#003370",
          "outline": "#727785",
          "on-tertiary-fixed": "#151c25",
          "surface-container-high": "#dce9ff",
          "on-secondary-fixed-variant": "#004491",
          "surface-container-highest": "#d3e4fe",
          "on-secondary": "#ffffff",
          "on-error": "#ffffff",
          "tertiary-container": "#6e7580",
          "surface-variant": "#d3e4fe",
          "on-background": "#0b1c30",
          "tertiary-fixed": "#dce3f0",
          "inverse-surface": "#213145",
          "primary-fixed": "#d8e2ff",
          "secondary": "#115cb9",
          "on-primary-container": "#fefcff",
          "tertiary-fixed-dim": "#c0c7d3",
          "surface-container-lowest": "#ffffff",
          "secondary-fixed": "#d7e2ff",
          "secondary-container": "#659dfe",
          "on-primary-fixed-variant": "#004396",
          "surface-dim": "#cbdbf5",
          "on-tertiary": "#ffffff",
          "inverse-on-surface": "#eaf1ff",
          "secondary-fixed-dim": "#acc7ff",
          "on-error-container": "#93000a",
          "on-secondary-fixed": "#001a40",
          "error-container": "#ffdad6",
          "on-surface": "#0b1c30",
          "surface-container": "#e5eeff",
          "on-surface-variant": "#424754"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "xl": "48px",
          "sm": "16px",
          "container-max": "1440px",
          "lg": "32px",
          "xs": "8px",
          "md": "24px",
          "base": "4px",
          "margin-mobile": "16px",
          "gutter": "24px"
      },
      "fontFamily": {
          "sans" : ['Poppins', 'sans-serif'],
          "body-md": ["Inter", "sans-serif"],
          "label-sm": ["Inter", "sans-serif"],
          "headline-md": ["Plus Jakarta Sans", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
          "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
          "display-lg": ["Plus Jakarta Sans", "sans-serif"],
          "label-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
          "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "600" }],
          "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
          "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
          "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
          "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}

